---
title: "Retrospectiva 2021"
description: |
  Este artigo faz uma retrospectiva dos eventos, projetos e observatórios que a ABJ realizou no ano de 2021. 
author:
  - name: Pedro Henrique Sperber 
    url: https://www.linkedin.com/in/pedro-henrique-sperber-rosa-26214116a/
date: 2022-02-04
preview: retrospectiva-2021.png
output:
  distill::distill_article:
    self_contained: false
---

Em 2021, seguindo o embalo do ano anterior, o trabalho da associação foi feito 100% remoto, ainda em decorrência da pandemia da COVID-19. Também foi um ano de expansão: aumentamos nossa equipe, a produção de artigos no Laboratório ABJ, o número de projetos, eventos e de associados! 

Assim como o artigo produzido no ano passado, esse texto visa compartilhar um pouco do que nós da ABJ produzimos durante o ano, trazendo informações sobre os projetos, eventos e leis que irão contribuir para a sociedade no país. 

Mas antes de avaliar e dar um panorama sobre os observatórios, projetos e demais tópicos envolvendo a ABJ em 2021, falaremos dos eventos que a associação realizou para pessoas associadas e não-associadas. 

# Eventos

Foi um ano de crescimento com relação aos eventos! Finalizamos a temporada de eventos com uma média de um encontro por mês, algo inédito para a ABJ.

Nossas conferências no Café Jurimétrico continuaram em formato online, com diversos convidados renomados trazendo conteúdos sobre a jurimetria e o direito. Foram 11 edições que abordaram temas como programação, direito previdenciário, arbitragem, as décadas de Jurimetria, jurimetria e a NLP no direito, judicialização da saúde, o mercado de capitais e o contencioso administrativo tributário. O resumo dos eventos você encontra [em nosso site](https://abj.org.br/eventos).

Além dos Cafés, exclusivos para pessoas associadas à ABJ, foram realizados 2 eventos de lançamentos de observatórios. Em maio, apresentando as análises sobre a atividade disciplinar da Comissão de Valores Mobiliários, foi lançada a primeira fase do [Observatório de Mercado de Capitais](https://www.youtube.com/watch?v=biud2tddj3E&t=28s). O evento contou com a participação do Presidente da CVM, Marcelo Barbosa, e dos escritórios Cescon, Barrieu, Flesch & Barreto Advogados; Guedes Nunes, Oliveira e Roquim; Mattos Filho, Veiga Filho, Marrey Jr. e Quiroga Advogados; Pinheiro Neto Advogados e Yazbek Advogados. 

O segundo evento de lançamento foi o  [Observatório da Insolvência: Rio de Janeiro](https://www.youtube.com/watch?v=CqcN9eboKSk), que analisou os processos de Recuperação Judicial do Rio de Janeiro. O evento contou com a participação do Presidente da ABJ, Marcelo Guedes Nunes, do advogado Marcelo Sacramone, da advogada Juliana Bumachar, e dos escritórios Ferro, Castro Neves, Daltro e Gomide Advogados, Galdino & Coelho Advogados, Rosman, Penalva, Souza Leão, Franco, Vale Advogados, Bumachar Advogados Associados e Sérgio Bermudes Advogados. 

# Projetos

No que diz respeito a projetos, 2021 trouxe à ABJ novos - e grandiosos! - desafios. Como foi o projeto com o Banco Interamericano de Desenvolvimento, o BID, para diagnosticar problemas e propor melhorias sobre o contencioso administrativo tributário brasileiro. Foram estudados dados do Conselho Administrativo de Recursos Fiscais (CARF) e extraídos dados estaduais e municipais para a pesquisa, além de ter contato com uma pesquisa de campo inovadora através de questionários bastante modernos. 

Fechando a aba de projetos, neste ano tivemos a oportunidade de continuar realizando os Observatórios da ABJ. Como citamos acima nos eventos, foram lançados os resultados das primeiras fases de dois dos nossos observatórios: Mercado de Capitais e Recuperações Judiciais do RJ. Mas também  trabalhamos ativamente   na terceira fase do Observatório da Insolvência em São Paulo, no Observatório Societário (que analisa discussões societárias dentro do Estado de São Paulo), e de Recuperações Judiciais no Rio Grande do Sul.

Todos os nossos projetos você encontra no [nosso site!](https://abj.org.br/cases)

# Parcerias e Ensino

Quanto às parcerias firmadas, o ano foi bastante produtivo para a ABJ. Dentre as colaborações, tivemos  a USP-EACH, em um trabalho voltado para o process mining, a Unichristus, no projeto sobre a Judicialização da Saúde, em parceria com a Justiça Federal do Ceará, o Departamento Nacional de Registro Empresarial e Integração
(DREI) Do Ministério da Economia, a fim de produzir avanços científicos no Mapa de Empresas.

Na área de estudos tivemos um grande marco para a associação e a jurimetria: a criação do novo Curso de Pós graduação em Jurimetria da PUC-SP, projeto de estudo  do Núcleo de Direito, Tecnologia e Jurimetria (NDTJ), que foi lançado em maio deste ano. Além do curso, seguimos realizando orientações aos pesquisadores somando mais de 20 pessoas auxiliadas em seus projetos pela equipe técnica da ABJ.

# Leis e resoluções relevantes

Também tivemos novidades em torno do universo da ciência de dados e do setor jurídico. Em abril, através da [Resolução n. 385/2021](https://atos.cnj.jus.br/atos/detalhar/3843), o CNJ criou o Núcleo de Justiça 4.0, que promove o desenvolvimento de tecnologias e de automação na gestão administrativa e na gestão de dados processuais do Poder Judiciário brasileiro, proporcionando maior agilidade e efetividade à Justiça. 

Finalizando o ano, o Presidente da ABJ, Marcelo Guedes Nunes, teve a honra de participar de um seleto grupo formado para trabalhar em estudos de soluções sobre APIs e mecanismos de integração entre sistemas. Esse grupo foi constituído pela [Portaria nº 261/2021](https://atos.cnj.jus.br/atos/detalhar/4176) assinada pelo Presidente, Ministro Luiz Fux. Sua finalidade é apresentar estudos e sugerir atos normativos a fim de estabelecer formas de colaboração e de participação da iniciativa privada na construção de soluções à Plataforma Digital do Poder Judiciário (PDPJ-Br). 

Na tentativa de definir o ano da ABJ em uma só palavra  acreditamos que a mais adequada seria: crescimento. Para 2022, esperamos poder continuar crescendo e cumprindo nossa missão de contribuir com a sociedade através dos nossos estudos.
