---
title: "As partes em processos administrativos sancionadores"
author: "Renata Hirota"
date: "8/28/2020"
output: 
  html_document:
    self_contained: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, results = "hide")
library(tidyverse)
library(patchwork)
```

# O que é o PAS? 

Antes de discutirmos a definição do Processo Administrativo Sancionador (PAS), precisamos entender o que é a Comissão de Valores Mobiliários (CVM) e quais suas competências.

A CVM é uma autarquia vinculada ao Ministério da Economia que fiscaliza a atuação de agentes no mercado de valores mobiliário. Dentre algumas de suas responsabilidades, estão o registro de companhias abertas, a organização das bolsas de valores, o credenciamento de auditores independentes e investigações em busca de irregularidades no mercado de capitais.

Dentre as fases da fiscalização, após a coleta de evidências de uma eventual irregularidade, destacam-se i) a fase pré-sancionadora, onde a CVM investiga se o objeto a ser discutido é, de fato, uma irregularidade a ser investigada e ii) a fase sancionadora, iniciada após a acusação do possível litigante através da instauração de um PAS.

O PAS, por sua vez, é um processo administrativo instaurado pela própria CVM que tem como objetivo investigar litígios dentro do mercado de capitais. Mais especificamente, de acordo com a própria CVM: 
"O Processo Administrativo Sancionador (PAS) é derivado de uma investigação realizada por meio de processo administrativo de caráter investigatório. É elaborado em uma das áreas técnicas da CVM, para o qual tenham sido encontrados indícios de autoria e materialidade, relativa a alguma irregularidade ocorrida no âmbito do mercado de capitais resultando em acusação."

Um dos recentes trabalhos da ABJ, chamado de Observatório CVM, teve como objetivo construir um boletim analítico com os principais indicadores e visualizações provenientes de uma análise quantitativa e exporatória de um conjunto de dados dos inquéritos instaurados pela CVM nos últimos anos. Dentre as etapas da análise, estava a estruturação e estudo da base que representava as partes dos processos. Um dos principais obstáculos dessa etapa, foi a categorização das partes dos processos para construir a informação "tipo de parte", fundamental para o andamento do projeto.

Neste artigo, apresentamos a metodologia empregada na construção do "tipo de parte" e das principais dificuldades enfrentadas no processo.

## Coleta e extruturação dos dados

- Falar sobre como coletamos os dados, de onde vieram etc
- Dificuldades técnicas no cruzamento de todas as bases, até chegar em duas bases consistentes, uma onde a observação é o resultado do PAS como um todo e outra, onde a observação é cada parte, de cada PAS.
- Apresentar um gráfico, talvez, mostrando a relação do número de partes em relação ao número de PAS, inferindo que, em média existem x partes para cada PAS (só pra encher linguiça, pra despertar a curiosidade do leitor)
- Falar sobre as características importantes para o observatório que coletamos
- Falar como fechamos a base de dados final (todos os filtros que fizemos nas partes [falecidos, ilegitimidade passiva etc]).

## Ainda falta uma variável

- Mostrar imagens descritivas (poucas) sobre a distribuição das partes (tipo PF/PJ), na_qualidade_de etc (o que for bem legal de mostrar)
- Ainda falta uma informação, o "tipo de parte", afinal, se ela não for construída, provavelmente abrirá um portal na Terra que trará criaturas do submundo pra devorar nossos cérebors (explicar pq o "tipo de parte" é importante).
- Falar sobre as dificuldades técnicas iniciais na construção da variável
- Explicar o passo a passo, detalhadamento, de como criamos a variável. (em cada passo, se possível, mostrar alguma visualização, poe ser grafico, imagem, tabela...)


## Tipo de parte

- Falar que foi um sucesso, conseguimos e é nois
- Mostrar a tabela final do tipo de partes
- Um ou dois gráficos mostrando a distribuição do tipo de partes.