---
title: "Novas perspectivas para 2021"
description: "Fórum aberto de jurimetria, atendimento a pesquisadores, novo cronograma de eventos e outras atividades previstas da ABJ para este ano"
author:
  - name: Bárbara Tassoni
date: 02-23-2021
output:
  distill::distill_article:
    self_contained: false
categories:
  - Geral
preview: "Novas perspectivas.png"
---

Na última sexta-feira de Janeiro/2021 (30), realizamos o primeiro Café 
Jurimétrico do ano. A nona edição do evento apresentou uma série de novidades 
que temos preparado na associação, principalmente para o nosso quadro de 
associados. 

Achamos que seria interessante toda a comunidade compartilhar de nossos avanços 
e queremos, cada vez mais, que participem conosco dessa história. Por isso, 
trazemos algumas das principais ações da ABJ para 2021 neste post. 

## Fórum aberto de Jurimetria 

O novo fórum de Jurimetria da ABJ está em fase final de configuração, mas já 
pode ser acessado através [deste link](https://forum.abj.org.br/). O nosso
objetivo é reunir toda a comunidade participante desse universo para discutir
sobre qualquer tipo de assunto relacionado à Jurimetria. 

Nos inspiramos em outros fóruns desse mesmo formato para trazer a possibilidade 
de incentivarmos os estudos e promover discussões relevantes acerca dos 
conceitos, técnicas, dificuldades e melhores práticas que podemos seguir dentro 
do tema. 

O mais bacana desse novo canal de contato é que, além de conseguirmos promover 
um ambiente colaborativo e mais ágil para as respostas e debates, ele será 
aberto a todos que quiserem participar.

## Novo cronograma de auxílio a pesquisadores

Este, sem dúvida, é um projeto da ABJ que temos muito orgulho. Ao longo de 
nossos anos de atuação, tivemos a oportunidade de auxiliar diversos estudantes e
pesquisadores, não como mentores ou professores, mas na orientação de dúvidas e 
indicando possibilidades de pesquisa em seus estudos jurimétricos. 

Temos nos preparado para continuar e expandir cada vez mais essa ação que traduz
a maior missão da ABJ: reunir e incentivar pesquisadores que tenham interesse 
pelo estudo prático da jurimetria.

Para isso, este ano definimos uma agenda com horários fixos semanais destinados 
ao atendimento de pesquisadores (e grupos de pesquisa), com ênfase aos 
associados, que estejam com projetos em desenvolvimento e necessitem de 
orientações sobre metodologia, dúvidas em utilização e extração de dados, 
análises simples, conceitos de jurimetria, entre outras necessidades.

Por conta da demanda, os horários tendem a ser disputados e, por termos uma 
agenda dupla, de associados e não associados, o tempo para conseguirmos realizar
o atendimento pode variar bastante. Se tiver interesse em saber mais, você pode
entrar em contato conosco através do nosso e-mail [contato@abj.org.br](contato@abj.org.br) ou se associando através do [nosso site](https://abj.org.br/associados/).

## Novo cronograma de eventos

Nada melhor do que podermos promover debates relevantes através de nossos 
tradicionais Cafés Jurimétricos. E a grande novidade para este ano é que em 2021
o nosso café será mensal. 

O evento, pensado para nossos associados, ganha mais frequência e buscará a 
aproximação com o quadro associativo. Como este, em especial, é um evento 
fechado, também estamos programando outros momentos ao longo do ano para 
promover e divulgar novos conteúdos e discussões com toda a comunidade.

## Área do associado, sistema de associação 

Estamos bastante animados com as novidades e a nova área do associado da ABJ é 
mais uma delas. Ainda em desenvolvimento, contará não só com uma versão 
atualizada do nosso Boletim Eletrônico -- que possui diferentes insights sobre os
dados do TJSP -- , mas também com uma relação completa de pacotes, projetos
desenvolvidos, download de bases de dados que disponibilizamos e várias
informações dos Observatórios da ABJ.

Enfim, 2021 será um ano de muito trabalho aqui na associação. Esperamos que 
essas novidades sejam só o começo e que vocês possam aproveitar cada uma delas.
Visite [nosso site](https://abj.org.br/) -- que está de cara nova --, fique por 
dentro dos próximos eventos, inscreva-se no fórum e continue nos acompanhando 
por aqui, no Lab. Vai ser incrível poder contar com todos vocês em 2021!

