---
title: "Um perfil dos leiloeiros dos processos de falência em São Paulo"
description: |
Este artigo busca compreender o perfil dos leiloeiros nos processos de falência em São Paulo
author:
  - name: Ricardo Feliz
    url: https://www.linkedin.com/in/ricardo-feliz-okamoto-a20344171/
date: "`r Sys.Date()`"
categories:
  - Falência
  - Leilão
  - Leiloeiro
  - Jurimetria
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)

```

```{r importacao}
# remotes::install_github("abjur/obsFase3")
# Import da base de todos os leilões
leiloes <- obsFase3::da_leilao_tidy

# selecionar todas as grafias possíveis de leiloeiros
todos_leiloeiros <- leiloes %>% 
  group_by(id_leiloeiro) %>% 
  select(leiloeiro, cpf_cnpj, id_leiloeiro, modalidade) %>% 
  unique() %>% 
  arrange(leiloeiro)
```

```{r arrumacao}
# Eu vou primeiro arrumar a base todos_leiloeiros, como forma teste. Quando eu conseguir arrumar essa base, eu vou pegar o código e repetir ele pra "leilões"
todos_leiloeiros <- todos_leiloeiros %>% 
  dplyr::mutate(
    leiloeiro_arrumado = dplyr::case_when(
      str_detect(leiloeiro, regex("ron.*faro|ron.*mon", ignore_case=TRUE)) ~ "Ronaldo Sérgio Montenegro Rodrigues Faro",
      str_detect(leiloeiro, regex("Cerello", ignore_case=TRUE)) ~ "Fernando José Cerello Gonçalves Pereira",
      str_detect(leiloeiro, regex("Alexandridis", ignore_case=TRUE)) ~ "Georgios José Ilias Bernabé Alexandridis",
      str_detect(leiloeiro, regex("Moretto", ignore_case=TRUE)) ~ "Gustavo Moretto Guimarães de Oliveira",
      str_detect(leiloeiro, regex("Thais Silva", ignore_case=TRUE)) ~ "Thais Silva Moreira de Sousa",
      str_detect(leiloeiro, regex("Macedo Campos", ignore_case=TRUE)) ~ "André Macedo Campos Toledo",
      str_detect(leiloeiro, regex("Sato", ignore_case=TRUE)) ~ "Antonio Hissao Sato Junio",
      str_detect(leiloeiro, regex("Wendell", ignore_case=TRUE)) ~ "Wendell Marcel Calixto Félix",
      str_detect(leiloeiro, regex("badolato", ignore_case=TRUE)) ~ "Cezar Augusto Badolato Silva",
      str_detect(leiloeiro, regex("Dannae", ignore_case=TRUE)) ~ "Dannae Vieira Avila",
      str_detect(leiloeiro, regex("Dora Plat", ignore_case=TRUE)) ~ "Dora Plat",
      str_detect(leiloeiro, regex("Zukerman", ignore_case=TRUE)) ~ "Fabio Zukerman",
      str_detect(leiloeiro, regex("Samuel", ignore_case=TRUE)) ~ "Gustavo Cristiano Samuel dos Reis",
      str_detect(leiloeiro, regex("Moy", ignore_case=TRUE)) ~ "Renato Schlobach Moysés",
      str_detect(leiloeiro, regex("Uilian", ignore_case=TRUE)) ~ "Uilian Aparecido da Silva",
      str_detect(leiloeiro, regex("Villa Nova", ignore_case=TRUE)) ~ "Sérgio Villa Nova de Freitas",
      str_detect(leiloeiro, regex("Boya", ignore_case=TRUE)) ~ "Eduardo Jordão Boyadjian",
      str_detect(leiloeiro, regex("Franklin", ignore_case=TRUE)) ~ "Renata Franklin Simões",
      str_detect(leiloeiro, regex("Cardoso", ignore_case=TRUE)) ~ "Danilo Cardoso da Silva",
      str_detect(leiloeiro, regex("Fidalgo", ignore_case=TRUE)) ~ "Douglas José Fidalgo",
      str_detect(leiloeiro, regex("Affonso", ignore_case=TRUE)) ~ "Alfio Carlos Affonso Zalli Neto",
      str_detect(leiloeiro, regex("Mega", ignore_case=TRUE)) ~ "Mega Leilões",
      str_detect(leiloeiro, regex("juiz|Furtado|adm|AJ|trustee", ignore_case=TRUE)) ~ "não leiloeiro",
    ),
    cpf_cnpj = dplyr::case_when(
      leiloeiro_arrumado == "Ronaldo Sérgio Montenegro Rodrigues Faro" ~ "08046824887",
      leiloeiro_arrumado == "Fernando José Cerello Gonçalves Pereira" ~ "21989241883",
      leiloeiro_arrumado == "Georgios José Ilias Bernabé Alexandridis" ~ "25419334879",
      leiloeiro_arrumado == "Gustavo Moretto Guimarães de Oliveira" ~ " 28034586838",
      leiloeiro_arrumado == "Thais Silva Moreira de Sousa" ~ " 36171181862",
      leiloeiro_arrumado == "André Macedo Campos Toledo" ~ "",
      leiloeiro_arrumado == "Antonio Hissao Sato Junio" ~ "27110999890",
      leiloeiro_arrumado == "Wendell Marcel Calixto Félix" ~ "16239428884",
      leiloeiro_arrumado == "Cezar Augusto Badolato Silva" ~ "07538221808",
      leiloeiro_arrumado == "Dannae Vieira Avila" ~ "36947855829",
      leiloeiro_arrumado == "Dora Plat" ~ "07080906806",
      leiloeiro_arrumado == "Fabio Zukerman" ~ "21575323826",
      leiloeiro_arrumado == "Gustavo Cristiano Samuel dos Reis" ~ "27358397886",
      leiloeiro_arrumado == "Renato Schlobach Moysés" ~ "09141676858",
      leiloeiro_arrumado == "Uilian Aparecido da Silva" ~ "11645230821",
      leiloeiro_arrumado == "Sérgio Villa Nova de Freitas" ~ "33201862800",
      leiloeiro_arrumado == "Eduardo Jordão Boyadjian" ~ "12634759819",
      leiloeiro_arrumado == "Renata Franklin Simões" ~ "20538037890",
      leiloeiro_arrumado == "Danilo Cardoso da Silva" ~ "31191072800",
      leiloeiro_arrumado == "Alfio Carlos Affonso Zalli Neto" ~ " 39681014804",
      leiloeiro_arrumado == "Douglas José Fidalgo" ~ "16499659827",
      leiloeiro_arrumado == "Mega Leilões" ~ "03122040000102",
      TRUE ~ cpf_cnpj
    ),
    id_leiloeiro = dplyr::case_when(
      leiloeiro_arrumado == "Ronaldo Sérgio Montenegro Rodrigues Faro" ~ "6331",
      leiloeiro_arrumado == "Fernando José Cerello Gonçalves Pereira" ~ "5406",
      leiloeiro_arrumado == "Georgios José Ilias Bernabé Alexandridis" ~ "7633",
      leiloeiro_arrumado == "Gustavo Moretto Guimarães de Oliveira" ~ "7979",
      leiloeiro_arrumado == "Thais Silva Moreira de Sousa" ~ "34064",
      leiloeiro_arrumado == "André Macedo Campos Toledo" ~ "",
      leiloeiro_arrumado == "Antonio Hissao Sato Junio" ~ "858",
      leiloeiro_arrumado == "Wendell Marcel Calixto Félix" ~ "23601",
      leiloeiro_arrumado == "Cezar Augusto Badolato Silva" ~ "5393",
      leiloeiro_arrumado == "Dannae Vieira Avila" ~ "28025",
      leiloeiro_arrumado == "Dora Plat" ~ "5608",
      leiloeiro_arrumado == "Fabio Zukerman" ~ "5508",
      leiloeiro_arrumado == "Gustavo Cristiano Samuel dos Reis" ~ "5596",
      leiloeiro_arrumado == "Renato Schlobach Moysés" ~ "466",
      leiloeiro_arrumado == "Uilian Aparecido da Silva" ~ "26542",
      leiloeiro_arrumado == "Sérgio Villa Nova de Freitas" ~ "5604",
      leiloeiro_arrumado == "Eduardo Jordão Boyadjian" ~ "924",
      leiloeiro_arrumado == "Renata Franklin Simões" ~ "669",
      leiloeiro_arrumado == "Danilo Cardoso da Silva" ~ "7794",
      leiloeiro_arrumado == "Alfio Carlos Affonso Zalli Neto" ~ "21977",
      leiloeiro_arrumado == "Douglas José Fidalgo" ~ "5535",
      leiloeiro_arrumado == "Mega Leilões" ~ "5426",
      TRUE ~ id_leiloeiro
    )
  ) 
```


