---
title: "Questões sobre indicadores de acesso à justiça"
description: |
  Este artigo busca discutir a mensuração do acesso à justiça. Como podemos medir? Quais são os problemas teóricos em realizar esta tarefa? Essas são algumas questões que serão debatidas. 
author:
  - name: Ricardo Feliz Okamoto
    url: https://www.linkedin.com/in/ricardo-feliz-okamoto-a20344171/
date: 2022-04-25
output:
  distill::distill_article:
    self_contained: false
---

A questão do acesso à justiça começou a ser discutida mundialmente após os estudos de Cappelletti e Garth em 1975 no Projeto Florença. Os autores identificaram três movimentos de ampliação do acesso à justiça no mundo, que eles denomineram de três "ondas". 

A primeira onda compreendeu o problema de acesso à justiça como um problema de falta de acesso por falta de recursos, ou seja, muitas pessoas não conseguiam resolver seus problemas judicialmente pois não tinham dinheiro para pagar as custas judiciais, advogados ou até o deslocamento até os tribunais para realizar audiências. Deste problema, nasceu a primeira onda, sobre hipossuficientes. 

A segunda onda compreendeu o acesso à justiça de direitos que não tinham algum sujeito para defendê-los. Era o problema dos direitos difusos e coletivos. A grande questão desses direitos era como defender um direito de que ninguém é titular? Pode um cidadão qualquer propor uma ação para defender um direito que é de todos? E se algum outro cidadão discordar da forma como o direito está sendo defendido? Ele pode propor outra ação, distinta daquela inicial, para tratar do mesmo problema? Ou ele poderia anular a ação da qual ele discorda? Por causa desse tipo de questão, a respeito da titularidade das ações coletivas (ou melhor dizendo, a respeito de quem pode representar a coletividade e defender os seus direitos jurisdicionalmente), surgiu a segunda onda de acesso à justiça: a onda de direitos difusos e coletivos. 

Por fim, a terceira onda veio da percepção de que alguns conflitos não poderiam ser resolvidos judicialmente, ou que poderiam ser melhor resolvidos fora da arena judicial. Essa terceira onda trouxe, então, para as discussões sobre acesso à justiça a noção de que "justiça" não significa apenas Judiciário; essa onda, então, ampliou as formas de prestação da justiça, trazendo para o centro os mecanismos adequados de solução de conflitos (MASCs), tais como a mediação, a conciliação e a arbitragem. Há quem chame os MASCs de mecanismos *alternativos* de resolução de conflito, entretanto, chamar de esses mecanismos de "alternativos" acaba por diminuir a sua importância, por ressaltar o quanto que o Judiciário é a forma "principal" (em detrimetno de "alternativa") de resolução de conflitos. Por essa razão, optamos por chamar os MASCs de mecanismos *adequados* de resolução de conflitos, uma vez que alguns conflitos são melhor endereçados por meio de métodos de solução de conflito amigáveis, não litigiosos e informais. A essa terceira onda, então, é a onda de procedimentos e instituições para aprimorar o sistema de processamento de litígios. 

Cada uma dessas três ondas está relacionada a soluções específicas para o acesso à justiça. A primeira onda se relaciona à criação da Defensoria Pública e dos Juízados Especiais Cíveis (JEC), bem com se à justiça gratuita e e à assistência judiciária. A segunda onda se relaciona às novas atribuições do Ministério Público, dadas pela Lei de Ação Civil Pública e consagrada pela Constituição Federal. E a terceira onda se relaciona à Lei de Arbitragem e aos CEJUSCs. 

Hoje em dia, já se fala em 7 ondas de acesso à justiça, e, no lugar do Projeto Florença, há o _Global Access to Justice Program_. Apesar das novas ondas, discutiremos a mensuração apenas das três ondas clássicas de acesso à justiça, uma vez que as demais ondas ainda não possuem contornos muito bem delimitados, o que dificultaria a nossa discussão. 

Feita essa última consideração, podemos prosseguir à discussão central do texto. O que queremos discutir a seguir é como mensurar o desempenho do acesso à justiça a respeito dessas três ondas clássicas. Este texto não pretende dar alguma resposta ou solução final à mensuração das ondas de acesso à justiça, mas busca dar um empurrão no debate com a comunidade a respeito de como realizar esta tarefa. Tampouco este texto busca examinar com minúcia todas as dimensões da mensuração dos conceitos. O que este texto busca fazer é dar ideias e problemas relacionados a essa mensuração. Cada onda irá trazer uma problemática diferente na mensuração e, decerto, não será uma análise exaustiva dos indicadores possíveis, nem de seus problemas. 


# Onda 1

A respeito da primeira onda, podemos pensar em algumas medidas importantes para avaliar a prestação do acesso à justiça. Para este texto, iremos apenas discutir a mensuração da _justiça gratuita_. Uma forma fácil de medir a justiça gratuita é por meio da proporção entre o total de processos em que a justiça gratuita foi deferida e o total de processos em que a justiça gratuita foi solicitada.

$$
justica\:gratuita = \frac{pedidos\:de\:justica\:gratuita\:deferida} {total\:de\:pedidos\:de\:justica\:gratuita}
$$
O que devemos esperar desse indicador? Esse indicador poderá variar de 0 a 1, em que 1 significa que todos os pedidos de justiça gratuita foram deferidos e 0, que nenhum pedido foi aceito. Nunca encontraremos nenhum dos dois polos, a realidade deve estar em algo entre 1 e 0. O que precisamos saber é o que significa encontrar, por exemplo, que 0,6 (ou 60%) dos pedidos de justiça gratuita foram deferidos? Isso seria melhor do que 0,4 (40%)? Quanto mais próximo de 1 melhor? Não necessariamente. Nem todos os pedidos de justiça gratuita devem ser deferidos, pois pode haver fraude no pedido (ou seja, o autor da demanda pode estar afirmando enganosamente ser pobre para não pagar as custas judiciais), ou simplesmente porque o que uma pessoa considera como ser pobre é diferente dos critérios do Judiciário para tanto, gerando um desencontro de expectativas entre os usuários do sistema de justiça e os seus servidores. Então para sabermos interpretar o que este indicador está nos mostrando, precisamos compreender a realidade a respeito dos *pedidos* de justiça gratuita. Algumas perguntas importantes são:
- Qual é a chance de um pedido de justiça gratuita ser fraudulento? 
- Qual é a chance de um pedido de justiça gratuita estar em descompasso com o que o Judiciário considera como "hipossuficiente"?
- Qual é a chance de o requerente de justiça gratuita não conseguir provar a sua situação de insuficiência financeira (não porque ele não o seja hipossuficiente, mas simplesmente porque ele não conseguiu reunir os documentos necessários para tanto)?

Essas perguntas todas importam na medida em que elas nos informam sobre qual é a proporção de deferimento esperado. O que queremos é maximizar a quantidade de deferimentos de "pedidos reais" e minimizar a quantidade de deferimentos de "pedidos falsos". Por "pedidos reais"  me referiro apenas aos pedidos de justiça gratuita que realmente expressam a necessidade financeira de alguém. E por "pedidos falsos" me refiro aos pedidos de justiça gratuita que eram fraudulentos ou que não expressavam uma real necessidade financeira de alguém. A depender da quantidade de *pedidos* de cada uma dessas categorias, teremos uma determinada expectativa a respeito do indicador. Por exemplo, se 30% dos pedidos forem "falsos", então temos de ter uma expectativa de que quanto mais próximo de 0,7 (70%), melhor será o acesso à justiça para hipossuficientes. Se encontrássemos por exemplo, dentro desse mesmo contexto, um resultado muito inferior aos 70% esperados, poderíamos usar isso como um indicador de que os juízes estão sendo muito rígidos na concessão de justiça gratuita. Mas ainda, mesmo se encontrássemos um valor próximo dos 70% isso não significaria que o acesso à justiça está bom. Poderia ser que muitos "pedidos reais" estão sendo indeferidos, mas que eles estão sendo "compensados" por uma altissima taxa de deferimento dos "pedidos falsos". 

A grande questão de um indicador desses é que para se ter essa expectativa a respeito dos resultados do indicador, é preciso realizar estudos robustos e contínuos sobre a realidade por trás dos pedidos de justiça gratuita. Um estudo desses seria demorado e caro. Quantitativamente, conseguiríamos apenas determinar a taxa de deferimento de justiça gratuita, mas não conseguiríamos delimitar um parâmetro para a interpretação desse resultado. 

# Onda 2

Sobre a segunda onda, vamos tratar de um outro problema sobre indicadores sobre a Justiça. 

Uma forma de se medir o acesso à justiça da segunda onda (sobre direitos difusos e coletivos) seria tentar mensurar quantas questões coletivas chegam até o Judiciário. Esse número teoricamente é fácil de se obter, pois poderia ser calculado como a soma de todas as ações que dizam respeito a algum tema de interesse coletivo. 

Pode até existir alguma dificuldade em se decidir que ações deveriam entrar ou não nessa soma. Em geral, com certeza, consideraríamos todas as ações coletivas, tais como ações civis públicas, ações populares, mandados de segurança coletivos, habeas corpus coletivos, mandados de injunção e ações constitucionais (ADC, ADI, ADI por omissão e ADPF). Mas poderíamos nos questionar se devemos considerar também ações ordinárias. Associações podem entrar com ações ordinárias para resolver os problemas coletivos; o Ministério Público, a fim de proteger o meio ambiente, pode ingressar com alguma ação de obrigação de não fazer, a fim de cessar um dano ambiental; pode-se até, por meio de ação de indenização por danos morais, exigir a reparação a um grupo que foi prejudicado. De alguma forma, então, poderíamos considerar, além de todas as ações coletivas, todas as ações em que consta alguma entidade representativa da coletividade em um dos polos da ação, sejam organizações da socidade civil (como associações), seja o Ministério Público. Mas ainda, poderíamos pensar se ações sem alguma coletividade em um dos polos deveria ser considerada? É muito frequente nas discussões sobre a judicialização de direitos sociais que indivíduos defendam seus próprios direitos sociais subjetivos contra o Estado. É o que acontece na judicialização da saúde (em que indivíduos, e não associações, requerem a prestação de algum medicamento ou serviço médico para o SUS), ou na judicialização das creches (em que indivíduos, e não associações, requerem vaga em creches públicas). Nesses casos todos, a ação proposta não é uma ação coletiva (mas talvez desse ser), e tampouco possui em um dos polos alguma entidade representativa de interesses coletivos, tais como associações, ou o Ministério Público. Neste caso, poderia surgir uma dúvida se devemos considerar estas ações ou não.

Então, poderia até existir alguma dificuldade em se decidir o que considerar ou não nessa soma, mas uma vez superado este problema, conta é fácil de se realizar. O grande problema desse número é a sua interpretação. O que acontece é, por mais que eu tenha a soma de todas as ações coletivas, como saber se esse número é bom ou ruim? Como saber se esse número indica que o acesso à justiça de direitos difusos e coletivos está sendo efetivado ou não? A questão é que precisamos de algum comparativo; esse número deve ser medido em relação a algo. E o problema é justamente definir que "algo" é este. 

Uma primeira ideia seria a de comparar a quantidade de ações coletivas em relação ao total de ações no Judiciário. Mas se essa for a comparação, então como interpretar seu resultado? Essa taxa iria variar de 0 (não há ações coletivas) a 1 (todas as ações do Judiciário dizem respeito a ações coletivas). E o que significaria essa taxa? Será que quanto maior a proporção, mais efetivo estará sendo o acesso à justiça desses direitos? Não parece que seja isso. Neste caso, pouco importa a proporção de casos em relação ao todo, pois o Judiciário é sede de muitos outros conflitos, que não possuem natureza coletiva. Então é esperado que a proporção dessas ações no total seja baixa, sendo, portanto, pouco relevante essa comparação.

Uma segunda ideia seria a de comparar as ações coletivas que entram na arena judicial com a quantidade de casos envolvendo direitos difusos e coletivos no mundo real. Ou seja, quantos conflitos envolvendo direitos difusos e coletivos existem no mundo, e quantos desses conflitos chegam até a arena judicial? Com aquela soma que descrevemos anteriormente, teríamos acesso à segunda parte da pergunta ("quantos conflitos chegam até a arena judicial?"), mas não teríamos informação alguma sobre a primeira pergunta ("quantos conflitos envolvendo direitos difusos e coletivos existem no mundo?"). Acontece que não é fácil (e, talvez, sequer possível) de se obter esse número. Sem informações sobre quais conflitos que se travam no mundo real, não conseguimos ter ideia de quantos conflitos coletivos estão, de fato, conseguindo chegar até a arena judicial. Assim, o indicador poderia ser:

$$
direitos\:difusos\:e\:coletivos = \frac{acoes\:coletivas} {conflitos\:coletivos\:no\:mundo}
$$

Então, o que esse segundo problema está indicando é que devemos olhar para as ações do Judiciário, em comparação com o mundo real; este problema nos chama a atenção para a dimensão do viés de seleção dos problemas que chegam ao Judiciário, ou seja, quais casos do mundo real são "selecionados" para chegar até os tribunais? 

# Onda 3

Por fim, podemos olhar para a terceira onda, de conflitos que seriam melhor resolvidos fora da arena judicial. Neste caso, vamos fazer algo um pouco diferente. Ao invés de propormos um indicador e discuti-lo, vamos usar as discussões dos indicadores anteriores para avaliar um indicador já existente, criado pelo  Grupo de Pesquisa LIODS e pelo CNJ^[Disponível em: https://www.cnj.jus.br/wp-content/uploads/2021/04/Relatorio_Indice-de-Acesso-a-Justica_LIODS_29-4-2021.pdf]. O indicador é um indicador anual expresso pela seguinte fórmula:

$$
taxa\:de\:conciliacao\:(por\:ano) = \frac{quantidade\:total\:de\:sentencas\:homologatorias\:de\:acordo} {quantidade\:total\:de\:sentencas}
$$

O que queremos discutir é o que essa taxa está nos indicando e como interpretá-la. A primeira informação a que devemos nos atentar é que essa taxa varia de 0 a 1, em que 0 significa que nenhum acordo é homologado e 1 significa que todos os processos acabam com um acordo entre as partes. O que seria uma taxa desejável? Quanto mais próximo de 1, melhor? E se a proporção de acordos for alta, isso necessariamente significa que a conciliação é alta? 

Essa interpretação é difícil, pois não temos um parâmetro de quantos processos deveriam acabar em acordos. Mas o que podemos ter certeza é que, mesmo se encontrássemos uma taxa de 1, isso não significaria que o acesso à justiça na terceira onda está sendo efetivo. Isso pode significar apenas que todos os conflitos que chegam até o Judiciário forem resolvidos de forma amigável. A realidade, entretanto, poderia ser a de que muitos conflitos que se travam no mundo real não estão conseguindo chegar na arena judicial por alguma barreira de acesso à justiça e, por isso, que observamos no Judiciário uma taxa de conciliação tão alta. Ou ainda, uma taxa alta de conciliação poderia indicar que alguns _players_ do Judiciário estão usando como estratégia de litigância a conciliação, talvez como uma forma de evadir da decisão judicial. Então voltamos ao ponto de partida: precisamos ter parâmetros interpretativos para os indicadores, e estes parâmetros dependem de se estudar, menos a resposta do Judiciário aos problemas que lhe chegam, e mais a realidade pré-judicial, ou ainda a natureza das demandas que chegam até o Judiciário.  

# Conclusão

Para todas as ondas de acesso à justiça, discutimos indicadores que poderiam nos dizer se o acesso à justiça está sendo efetivado ou não. O objetivo ao se discutir esses indicadores era, menos conceituar e propor indicadores, e mais discutir problemas gerais de indicadores. Apresentamos ao longo das ondas 1 e 2 de acesso à justiça problemas relacionados à interpretação dos indicadores. Na primeira onda o problema apareceu como um viés de seleção entre os pedidos em comparação com os deferimentos; e na segunda onda, como um viés de seleção entre os casos do mundo real em comparação com os casos que chegam até a arena judicial. Para a terceira onda, utilizamos um indicador existente para pensá-lo criticamente, a partir das reflexões trazidas nas outras duas ondas. 

A ideia deste texto era suscitar um debate de mensuração do acesso à justiça, bem como o de estimular pesquisas que caminhem para este sentido. 
