---
title: "Metodologia de Pesquisa em Jurimetria: um começo"
description: |
  Toda pesquisa em jurimetria precisa passar por quatro etapas que exigem cuidados metodológicos específicos: listagem de processos, extração de dados, tratamento dos dados e análise. Neste texto, inauguramos uma série de postagens que vão se tornar um livro da ABJ sobre metodologia de pesquisa em jurimetria.
author:
  - name: Ricardo Feliz
    url: https://www.linkedin.com/in/ricardo-feliz-okamoto-a20344171/
date: 2023-08-04
output:
  distill::distill_article:
    self_contained: false
preview: EXT-2023.png
categories:
  - Metodologia
  - Pesquisa
---

Toda pesquisa em jurimetria precisa passar por quatro etapas que exigem cuidados metodológicos específicos: listagem de processos, extração de dados, tratamento dos dados e análise. Hoje, inauguramos uma série de postagens que vão se tornar um livro da ABJ sobre metodologia de pesquisa em jurimetria.

Neste post inicial, vamos passar pelas 4 etapas que toda pesquisa em jurimetria deve ter. Nos posts seguintes, detalharemos técnicas específicas que são utilizadas e cuidados metodológicos que devemos ter em cada uma das etapas. A ideia dos posts que vão se seguir é que eles sejam curtos e concisos e que, com a somatória de todos eles, seja possível compor uma metodologia completa em jurimetria. 

Antes de começarmos, é preciso fazer uma breve nota inicial: essas 4 etapas são etapas metodológicas; entretanto, elas não substituem algumas fases anteriores e necessárias a toda e qualquer pesquisa científica: a definição de objetivos gerais e específicos, a criação de uma pergunta de pesquisa e a elaboração teórica do problema de pesquisa. Essas partes anteriores são _pressupostas_ ao que veremos a seguir. 

## Listagem de processos

A listagem de processos é a etapa inicial de toda pesquisa quantitativa em Direito. O **objetivo** desta etapa é delimitar todos os processos que estarão dentro do escopo da pesquisa. Requer-se, portanto, que a pesquisa já tenha um objetivo claro. Aqui não estamos falando da delimitação do escopo da pesquisa em si, mas sim de uma situação em que o escopo _já foi delimitado_ e, a partir disso, queremos extrair os processos relacionados.

O que veremos nos posts relacionados à listagem de processos são **métodos e técnicas** que podemos empregar para fazer essa listagem e o impacto de cada uma delas nos resultados da pesquisa. Além disso, discutiremos alguns cuidados metodológicos que devemos ter ao realizar a listagem. 

O **resultado** dessa etapa será sempre a produção de uma lista, contendo todos os processos que se enquadram no escopo. Não necessariamente essa lista será utilizada por completo, pois é possível, por exemplo, fazer pesquisas por amostras.

## Extração das informações

Uma vez que todos os processos a serem analisados estejam listados, passamos para a extração dos dados, ou seja, passamos para as informações que serão analisadas. Às vezes, a etapa de extração das informações acaba coincidindo com a etapa de extração das informações, mas como já adiantamos, vamos separar analiticamente estas duas etapas. 

O **objetivo** da etapa de extração das informações é coletar os dados que serão relevantes sobre o objeto da análise (no caso, processos). 

Há diversas **técnicas** de extração das informações, algumas automatizadas (normalmente, para informações mais superficiais do processo) e outras manuais (normalmente, para informações que envolvem a leitura de documentos processuais, tais como sentenças, acórdãos e petições). Os textos relacionados a esta etapa metodológica vão nos ajudar a compreender (1) _quando_ devemos fazer extrações manuais ou automatizadas; (2) _como_ funciona cada uma dessas técnicas e (3) _quais_ são os cuidados metodológicos que devemos ter com cada técnica empregada. 

O **resultado** dessa etapa será a construção de uma base de dados bruta, em que cada linha dessa base é a nossa unidade observacional (isto é, o objeto que estamos tentando estudar) e cada coluna dessa base é uma informação a respeito do nosso objeto de análise. 

## Tratamento dos dados

O resultado da etapa anterior é a produção de uma base de dados _bruta_. Mas, muitas vezes, não conseguimos analisar bases nesse estágio, por possuírem muitos problemas. Por isso, há uma fase de transição entre a extração dos dados e a sua análise, que é a fase de tratamento dos dados. O **objetivo** dessa fase é transformar uma base bruta em uma base arrumada, que será a utilizada para as análises. 

O que veremos são, novamente, as **técnicas** de tratamento dos dados e os **cuidados metodológicos**. Assim como na etapa de extração das informações, existem procedimentos de tratamento tanto manuais quanto automatizados. 

O resultado, como já foi adiantado, será a produção de uma base limpa e arrumada, pronta para a análise. 

## Análises

A fase de análises é a fase final da pesquisa, cujo objetivo central é utilizar os dados para responder às perguntas de pesquisa. Existe ainda uma etapa posterior, que é a fase da comunicação da pesquisa. Entretanto, essa fase já não diz respeito tanto à metodologia, mas sim à escrita e ao estilo de cada pesquisador. Por isso, não iremos abordar essa etapa. 

Há vários **métodos e técnicas** para fazer essas análises. Podemos usar métodos puramente quantitativos, bem como métodos mistos (CRESWELL, John; CLARK, Vicki  (2013). Pesquisa de Métodos Mistos). Dentre os métodos puramente quantitativos, podemos utilizar técnicas de estatística descritiva apenas, ou técnicas que já envolvem modelagem estatística. Veremos, então, quando cada escolha deve ser feita e quais cuidados devemos tomar em cada análise. 

Além disso, existem análises que possuem **interpretações** específicas no contexto jurídico. Iremos abordar estes pontos também.

O resultado dessa etapa deverá ser a produção de um relatório de pesquisa.

## Conclusão

Vimos as etapas metodológicas de uma pesquisa em jurimetria. Conhecer essas etapas de forma ampla é importante para se ter uma visão holística sobre o tema. A partir desse sobrevoo geral na metodologia de pesquisa, seguiremos com uma sequência de textos para trazer mais detalhes sobre cada etapa. 

Os textos seguintes não seguirão, necessariamente, a ordem cronológica da pesquisa. Isto é, não esgotaremos todas as explicações da etapa 1 antes de começarmos a falar da etapa 2 e assim por diante. Estaremos, constantemente, atualizando o blog com textos sobre alguma dessas 4 etapas. A coletânea de todos os textos irá formar um conhecimento bem sedimentado sobre metodologia de pesquisa em jurimetria. 
