---
title: "Levantamentos feitos pela ABJ"
description: "Com frequência, recebemos pedidos de dados para pesquisas acadêmicas. Estes são alguns dos principais levantamentos que fizemos em 2020"
author:
  - name: Renata Hirota
    url: https://twitter.com/renata_mh
date: 03-22-2021
output:
  distill::distill_article:
    self_contained: false
---

O apoio a pessoas pesquisadoras que tenham interesse pelo estudo prático da 
jurimetria é uma missão da ABJ que tem sido exercida ao longo dos anos de 
atuação da associação. Em 2020, tivemos uma grande procura de pessoas, 
principalmente associadas, que entraram em contato para pedir ajuda com seus 
respectivos projetos de pesquisa empírica.

Além de orientação em possíveis dúvidas relacionadas a jurimetria, um dos 
pedidos recorrentes é de auxílio na extração e levantamento de dados 
processuais. 

A seguir, listamos alguns levantamentos feitos durante o ano de 
2020 que podem ser de interesse. Esperamos poder auxiliar mais pessoas e 
continuar nos envolvendo com pesquisas sobre diversos temas da jurimetria!

## Eleições 2020: processos criminais

A pedido do G1, a ABJ realizou o levantamento de todos os processos criminais em
que pessoas candidatas às eleições municipais de 2020 em São Paulo eram rés. Os 
dados foram obtidos com consulta ao Tribunal de Justiça de São Paulo (TJSP) pelo 
número de CPF das partes que, no caso de candidatos políticos, são 
disponibilizados pelo Tribunal Superior Eleitoral (TSE).

Os dados foram utilizados na matéria [Candidatos em SP são réus em mais de 500 processos criminais; lista de crimes inclui tortura, homicídio e violência doméstica](https://g1.globo.com/politica/eleicoes/2020/eleicao-em-numeros/noticia/2020/11/09/candidatos-em-sp-sao-reus-em-mais-de-500-processos-criminais-lista-de-crimes-inclui-tortura-homicidio-e-violencia-domestica.ghtml), publicada em novembro. Os
principais resultados também foram replicados em [reportagem do Fantástico](https://g1.globo.com/fantastico/noticia/2020/11/15/exclusivo-investigacoes-revelam-planos-do-crime-organizado-para-se-infiltrar-no-poder.ghtml).

## Reincidência criminal

Um dos pesquisadores que entrou em contato conosco, doutorando em Economia em 
Yale, nos procurou para que o ajudássemos com a coleta de dados para a sua 
pesquisa sobre reincidência criminal.

Foram levantados dados de processos penais de primeiro e segundo grau, com 
informações básicas dos casos como assunto, classe, data de distribuição, 
comarca e número do processo. Além disso, também foram identificados os nomes 
das partes disponíveis a partir dos diários de justiça eletrônicos.

## Recuperações judiciais

A ABJ também fez um levantamento de processos para um associado cujo tema de 
pesquisa envolve o estudo empírico de recuperações judiciais. Os dados foram 
obtidos mediante consulta no banco de sentenças e-SAJ de processos com a classe
"Recuperação Judicial", e depois filtrados para obter apenas as varas 
empresariais.

A parceria ainda rendeu um artigo no [Lab ABJ](http://lab.abj.org.br/posts/2021-03-09-recuperao-judicial-e-manuteno-de-empregos/), onde é analisada a relação entre recuperações judiciais e a manutenção de 
empregos.

## Improbidade administrativa

Para este projeto de conclusão de curso, foram levantados os acórdãos 
relacionados a três assuntos específicos, dentro do contexto de improbidade 
administrativa: Dano ao Erário, Enriquecimento ilícito e Violação aos Princípios 
Administrativos.

A ideia por trás da pesquisa era verificar se há diferença significativa entre 
as condenações por improbidade administrativa dentre as modalidades, devido a 
uma suposta subjetividade nos critérios para condenação em casos de improbidade 
administrativa por violação aos princípios administrativos.

## Contratos de franquias

Nós também realizamos em 2020 um levantamento sobre contratos de franquias para 
um projeto de iniciação científica de um pesquisador que, posteriormente, passou
a integrar a equipe da ABJ.

A parte quantitativa do projeto passa pela análise de jurisprudência de 
contratos de franquia em São Paulo. A pesquisa busca responder, entre outras 
questões relacionadas à análise econômica do direito, quais são as 
características dos processos que estão relacionadas com a geração de litígios.

## Process mining e dados de varas empresariais

Outra pesquisa com a qual tivemos envolvimento em 2020 teve como tema o 
_process mining_, ou mineração de processos, área de pesquisa relacionada com o 
monitoramento e melhoria de processos operacionais baseados em registros de 
eventos.

O estudo, conduzido pelo grupo pesquisa em process mining da Escola de Artes, 
Ciências e Humanidades da Universidade de São Paulo, teve como base um 
levantamento de processos de varas empresariais em São Paulo, realizado pela 
ABJ. Neste caso, o maior interesse nos dados foram as tabelas de movimentações 
dos processos, a partir das quais é possível calcular o tempo entre algumas 
etapas processuais.

## IRDR - Tema n. 3

O tema de número 3 do Incidente de Resolução de Demandas Repetitivas (IRDR), que
versa sobre prestação contas, interesse de agir e lançamentos, é o assunto 
central de pesquisa para a qual a ABJ realizou levantamento de dados do TJSP.

Para esse levantamento, foram utilizadas duas estratégias: a primeira, a partir 
de pesquisa de palavras-chave na consulta de jurisprudência do TJSP; e a 
segunda, a partir da listagem de processos do primeiro grau em diários oficiais 
de justiça, filtrando os casos com base nos assuntos e menções a "prestação ou 
exibição de contas" nas movimentações.

## Lei Maria da Penha

Por fim, o Grupo de Jurimetria da Universidade de São Paulo, criado recentemente
por estudantes de graduação de diversas áreas, procurou a ABJ para pedir auxílio
em seu projeto de pesquisa sobre a Lei Maria da Penha.

Foram levantados informações de processos com assuntos relacionados à lei, como 
violência doméstica contra a mulher. Os casos foram analisados e comparados com 
outra pesquisa sobre a percepção da população sobre a lei.

