---
title: "Recuperação judicial e manutenção de empregos"
description: "A recuperação judicial alcança o objetivo de permitir a manutenção do emprego dos trabalhadores? O que diz a realidade empírica?"
author:
  - name: Tadeu Sena Alves
    url: {}
date: 03-09-2021
output:
  distill::distill_article:
    self_contained: false
---

O ambiente de negócios e o desenvolvimento econômico de um país sofre grande 
influência pelos resultados que a regulação da insolvência entrega na realidade 
prática. No Brasil, a lei 11.101/2005, que regula a recuperação judicial, 
extrajudicial e falência da sociedade empresária e do empresário^[Não se ignora
a existência de decisões judiciais autorizando o processamento de ações de 
Recuperação Judicial em favor de agentes econômicos que não estão 
necessariamente inseridos na moldura da sociedade empresária/empresário, tal 
como ocorre no processo n.º 0093754-90.2020.8.19.0001, em curso na 5ª Vara 
empresarial do Rio de Janeiro, em que figura como recuperandas a Associação 
Sociedade Brasileira de Instrução (ASBI) e o Instituto Cândido Mendes.], está na
ordem do dia das discussões.

Os números evidenciam essa constatação. Foram 7.365 pedidos de recuperação 
judicial entre 2015 a 2019, ultrapassando-se assim, os 5.062 pedidos formulados 
ao longo dos dez anos anteriores à vigência da lei (2005 a 2014)^[SERASA 
EXPERIAN. Indicadores econômicos. Disponível em: 
[https://www.serasaexperian.com.br/amplie-seus-conhecimentos/indicadores-economicos](https://www.serasaexperian.com.br/amplie-seus-conhecimentos/indicadores-economicos). Acesso em: 30 mar. 2020.]. 

A Lei 11.101/2005 sofreu recentemente alterações e incrementos com a edição da 
lei 14.112/2020. Contudo, o seu artigo 47 que define como um dos objetivos da 
recuperação judicial a manutenção dos empregos restou intacto^[Dentro desse 
objetivo mais amplo, estão contidos os objetivos específicos do artigo 47, a 
saber: (a) manutenção da fonte produtora; (b) manutenção dos empregos; (c)
preservação dos interesses dos credores. Sobre o tema, ver GOMES, Tadeu Alves 
Sena. A Atividade empresarial após a sentença da recuperação judicial: A 
concretização da manutenção da fonte produtora, dos empregos e dos interesses
dos credores. 2020. Dissertação (Mestrado) – Instituto Brasileiro de Ensino, 
Desenvolvimento e Pesquisa (IDP), Distrito Federal, 2020.].

Preservado que foi o referido objetivo de manter os empregados dos trabalhadores
através do instrumento processual da ação de recuperação judicial, seria 
coerente dizer que a não alteração do referido dispositivo significaria dizer 
que o legislador estaria satisfeito com os resultados obtidos na realidade 
empírica. Será?

O método científico da observação, do teste, da reunião e da manipulação de 
dados permite um exame da realidade de determinado fenômeno. Isso acontece por
intermédio de evidências que confirmem ou refutem uma teoria, ainda que haja
discordância sobre o valor dos resultados específicos encontrados^[ULEN, Thomas 
S. Um prêmio Nobel para a ciência jurídica: teoria, trabalho empírico e o método
científico no estudo do direito. In: PORTO, Antonio Maristrello; SAMPAIO, 
Patrícia (org.). Direito e economia em dois mundos: doutrina jurídica e pesquisa
empírica. Rio de Janeiro: FGV, 2014, p. 54.].
